fix: Regex being ignored when there is no colon in commit-msg

diff --git a/makeme b/makeme
--- a/makeme
+++ b/makeme
@@ -583,6 +583,7 @@ refactor: Change how bin/gxpm handle arguments
 
 For detailed info, please check https://www.conventionalcommits.org
 	'
+	exit 1
 }
 
 function main() {
@@ -610,10 +611,12 @@ function main() {
 	# get the first line of the commit message
 	START_LINE="$(head -n1 "${INPUT_FILE:="$1"}")"
 
-	if ! echo "$START_LINE" | grep -q -E '^Update .*|^Merge .*' && [[ ! "$START_LINE" =~ $regexp ]]; then
+	! echo "$START_LINE" | grep -q ':' && print_error "$START_LINE"
+	
+	if ! echo "$START_LINE" | grep -q -E '^Update .*|^Merge .*' \
+	&& [[ ! "$START_LINE" =~ $regexp ]]; then
 		# commit message is invalid according to config - block commit
 		print_error "$START_LINE"
-		exit 1
 	fi
 }
 
